// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://peepevzpoevctixwalhc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBlZXBldnpwb2V2Y3RpeHdhbGhjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDcwMTcyNDUsImV4cCI6MjA2MjU5MzI0NX0.mJfPvcsOBlJ91wxPm8hFwB692LS-zEcjKWSYYtzlLD4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);